# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '20190903-ModelTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 20190903-ModelTest
  pod 'dyfOAtestSDK',:path => '../hahahaha/suibian01.podspec'

  target '20190903-ModelTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '20190903-ModelTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
